export const sampleRentals = [
    {
        id: 1,
        userId: 1,
        userName: "Arjun Sharma",
        userEmail: "arjun.sharma@gmail.com",
        vehicleId: 102,
        vehicleModelName: "Hyundai Creta",
        vehicleRegsNo: "DL3CAF9988",
        vehicleBrand: "Hyundai",
        vehicleImageUrl: "https://imgd.aeplcdn.com/642x336/n/cw/ec/106815/creta-exterior-right-front-three-quarter-6.png?isig=0&q=80",
        type: "DAILY",
        status: "ACTIVE",
        checkoutDate: "2026-02-15",
        dueDate: "2026-02-25",
        remainingDays: 1,
        returnDate: null,
        extensionCount: 1,
        maxExtensionCount: 2,
        fineAmount: 0.00,
        finePaid: false,
        notes: "Customer requested child seat",
        isOverdue: false,
        overdueDays: 0,
        createdAt: "2026-02-15T10:00:00",
        updatedAt: "2026-02-20T09:00:00",
    },
    {
        id: 2,
        userId: 2,
        userName: "Priya Mehta",
        userEmail: "priya.mehta@gmail.com",
        vehicleId: 103,
        vehicleModelName: "Royal Enfield Classic 350",
        vehicleRegsNo: "MH12XY4455",
        vehicleBrand: "Royal Enfield",
        vehicleImageUrl: "https://www.royalenfield.com/content/dam/royal-enfield/motorcycles/new-classic-350/studio-shots/360/stealth-black/stealth-black-000.png",
        type: "WEEKLY",
        status: "OVERDUE",
        checkoutDate: "2026-02-10",
        dueDate: "2026-02-17",
        remainingDays: 0,
        returnDate: null,
        extensionCount: 0,
        maxExtensionCount: 2,
        fineAmount: 450.00,
        finePaid: false,
        notes: null,
        isOverdue: true,
        overdueDays: 7,
        createdAt: "2026-02-10T11:30:00",
        updatedAt: "2026-02-18T08:00:00",
    },
    {
        id: 3,
        userId: 3,
        userName: "Dev Rathore",
        userEmail: "dev.rathore@github.com",
        vehicleId: 101,
        vehicleModelName: "Honda Aviator",
        vehicleRegsNo: "UP76AB5467",
        vehicleBrand: "Honda",
        vehicleImageUrl: null,
        type: "DAILY",
        status: "RETURNED",
        checkoutDate: "2026-02-01",
        dueDate: "2026-02-07",
        remainingDays: 0,
        returnDate: "2026-02-07",
        extensionCount: 0,
        maxExtensionCount: 2,
        fineAmount: 0.00,
        finePaid: false,
        notes: "Returned on time, good condition",
        isOverdue: false,
        overdueDays: 0,
        createdAt: "2026-02-01T09:00:00",
        updatedAt: "2026-02-07T17:00:00",
    },
    {
        id: 4,
        userId: 4,
        userName: "Sneha Joshi",
        userEmail: "sneha.joshi@github.com",
        vehicleId: 105,
        vehicleModelName: "Tata Nexon EV",
        vehicleRegsNo: "GJ01EV7788",
        vehicleBrand: "Tata",
        vehicleImageUrl: null,
        type: "MONTHLY",
        status: "DAMAGED",
        checkoutDate: "2026-01-20",
        dueDate: "2026-02-20",
        remainingDays: 0,
        returnDate: "2026-02-18",
        extensionCount: 0,
        maxExtensionCount: 1,
        fineAmount: 5000.00,
        finePaid: true,
        notes: "Minor dent on rear bumper reported at return",
        isOverdue: false,
        overdueDays: 0,
        createdAt: "2026-01-20T10:00:00",
        updatedAt: "2026-02-18T15:30:00",
    },
    {
        id: 5,
        userId: 5,
        userName: "Rahul Verma",
        userEmail: "rahul.verma@example.com",
        vehicleId: 104,
        vehicleModelName: "Suzuki Access 125",
        vehicleRegsNo: "KA05TT1122",
        vehicleBrand: "Suzuki",
        vehicleImageUrl: null,
        type: "DAILY",
        status: "CANCELLED",
        checkoutDate: "2026-02-22",
        dueDate: "2026-02-24",
        remainingDays: 0,
        returnDate: null,
        extensionCount: 0,
        maxExtensionCount: 2,
        fineAmount: 0.00,
        finePaid: false,
        notes: "Customer cancelled due to personal reasons",
        isOverdue: false,
        overdueDays: 0,
        createdAt: "2026-02-22T08:00:00",
        updatedAt: "2026-02-22T09:00:00",
    },
];