export const sampleReservations = [
    {
        id: 1,
        userId: 1,
        userName: "Arjun Sharma",
        userEmail: "arjun.sharma@gmail.com",
        vehicleId: 102,
        vehicleModelName: "Hyundai Creta",
        vehicleRegsNo: "DL3CAF9988",
        vehicleBrand: "Hyundai",
        isVehicleAvailable: false,
        status: "PENDING",
        reservedAt: "2026-02-20T10:00:00",
        availableAt: null,
        availableUntil: null,
        fulfilledAt: null,
        cancelledAt: null,
        queuePosition: 2,
        notificationSent: false,
        notes: "Needs the vehicle for a family trip",
        createdAt: "2026-02-20T10:00:00",
        updatedAt: "2026-02-20T10:00:00",
        isExpired: false,
        canBeCancelled: true,
        hoursUntilExpiry: null,
    },
    {
        id: 2,
        userId: 2,
        userName: "Priya Mehta",
        userEmail: "priya.mehta@gmail.com",
        vehicleId: 105,
        vehicleModelName: "Tata Nexon EV",
        vehicleRegsNo: "GJ01EV7788",
        vehicleBrand: "Tata",
        isVehicleAvailable: true,
        status: "NOTIFIED",
        reservedAt: "2026-02-18T09:00:00",
        availableAt: "2026-02-23T08:00:00",
        availableUntil: "2026-02-25T08:00:00",
        fulfilledAt: null,
        cancelledAt: null,
        queuePosition: 1,
        notificationSent: true,
        notes: null,
        createdAt: "2026-02-18T09:00:00",
        updatedAt: "2026-02-23T08:00:00",
        isExpired: false,
        canBeCancelled: true,
        hoursUntilExpiry: 24,
    },
    {
        id: 3,
        userId: 3,
        userName: "Dev Rathore",
        userEmail: "dev.rathore@github.com",
        vehicleId: 103,
        vehicleModelName: "Royal Enfield Classic 350",
        vehicleRegsNo: "MH12XY4455",
        vehicleBrand: "Royal Enfield",
        isVehicleAvailable: true,
        status: "FULFILLED",
        reservedAt: "2026-02-10T11:00:00",
        availableAt: "2026-02-14T09:00:00",
        availableUntil: "2026-02-16T09:00:00",
        fulfilledAt: "2026-02-14T14:00:00",
        cancelledAt: null,
        queuePosition: 0,
        notificationSent: true,
        notes: "Customer picked up on time",
        createdAt: "2026-02-10T11:00:00",
        updatedAt: "2026-02-14T14:00:00",
        isExpired: false,
        canBeCancelled: false,
        hoursUntilExpiry: null,
    },
    {
        id: 4,
        userId: 4,
        userName: "Sneha Joshi",
        userEmail: "sneha.joshi@github.com",
        vehicleId: 101,
        vehicleModelName: "Honda Aviator",
        vehicleRegsNo: "UP76AB5467",
        vehicleBrand: "Honda",
        isVehicleAvailable: false,
        status: "CANCELLED",
        reservedAt: "2026-02-12T08:00:00",
        availableAt: null,
        availableUntil: null,
        fulfilledAt: null,
        cancelledAt: "2026-02-13T10:30:00",
        queuePosition: 0,
        notificationSent: false,
        notes: "Cancelled by user — found another vehicle",
        createdAt: "2026-02-12T08:00:00",
        updatedAt: "2026-02-13T10:30:00",
        isExpired: false,
        canBeCancelled: false,
        hoursUntilExpiry: null,
    },
    {
        id: 5,
        userId: 5,
        userName: "Rahul Verma",
        userEmail: "rahul.verma@example.com",
        vehicleId: 104,
        vehicleModelName: "Suzuki Access 125",
        vehicleRegsNo: "KA05TT1122",
        vehicleBrand: "Suzuki",
        isVehicleAvailable: true,
        status: "EXPIRED",
        reservedAt: "2026-02-15T07:00:00",
        availableAt: "2026-02-19T09:00:00",
        availableUntil: "2026-02-21T09:00:00",
        fulfilledAt: null,
        cancelledAt: null,
        queuePosition: 0,
        notificationSent: true,
        notes: "Customer did not show up for pickup",
        createdAt: "2026-02-15T07:00:00",
        updatedAt: "2026-02-21T09:00:00",
        isExpired: true,
        canBeCancelled: false,
        hoursUntilExpiry: 0,
    },
];