spring.application.name=SafarSetu-Vehicle-Management

# DB Configurations
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}

# Mail Config (Not Used)
spring.mail.host=in-v3.mailjet.com
spring.mail.port=587
spring.mail.username=e489cde40ad26a3d2205291065ea9619c8
spring.mail.password=your app password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

razorpay.key.id=${RAZORPAY_ID}
razorpay.key.secret=${RAZORPAY_SECRET}
razorpay.callback.base-url=${RAZORPAY_CALLBACK}

# Google Oauth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# Github Oauth
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.provider.github.user-name-attribute=id

# Cloudinary Configuration
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Increase file size limit if needed
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# GEMINI Configuration
gemini.api.key=${GEMINI_API_KEY}

# JWT Configurations
client.jwt.secret=${JWT_SECRET}

# Frontend url
client.frontend.user.url=${FRONTEND_URL_USER}
client.frontend.admin.url=${FRONTEND_URL_ADMIN}

# Admin Credentials
client.admin.email=${DEF_ADMIN_EMAIL}
client.admin.password=${DEF_ADMIN_PASSWORD}

# Oauth Fix
server.forward-headers-strategy=framework
spring.security.oauth2.client.registration.google.redirect-uri=https://safarsetu-backend-production.up.railway.app/login/oauth2/code/google